### ISSUE TITLE
Don't bake the NstDatabase.xml file into the core

### ISSUE THREAD

**Issue by ghost** [libretro/nestopia#25]
This is beyond stupid, and I just wasted _hours_ of my time trying to get Micro Mages added to the database so that a few of my friends and I could play 4 players over netplay.

**DO NOT DO THIS**, configuration files are meant to be configured. RetroArch warns that the file is missing, and the [docs][1] prompt you to download it yourself. This is incredibly misleading and infuriating. The decision to do this is incredibly misguided, since it assumes the set of NES games is fixed, which it definitely isn't as homebrew and commercial games are still developed.

[1]: https://docs.libretro.com/library/nestopia_ue/#nstdatabasexml

**Comment by keithbowes** [comment]
Yeah, I protested it when that commit was made, to no avail.  I think the logic is that so that people can just download the core from RetroArch without worrying about getting the database.  I haven't been so bold as to revert the baked-in database, as that's obviously what the main developers want, but I have written a Python script to convert the NstDatabase.xml file into a byte array, and was going to send a PR of it along with the update to Nestopia 1.51.0 (as its NstDatabase.xml file has been updated), when I figure out the best way to do it.

BTW, other emulators have built-in databases as well, but they seemingly don't have Nestopia's problem of not working if a database entry isn't available.  I haven't encountered a homebrew that doesn't work in Nestopia (except when it uses an unsupported mapper), but maybe I just haven't found anything that arcane.

Though, I do agree that either the baked-in database should be reverted or the documentation should be updated.

**Comment by rdanbrook** [comment]
The database is really there to handle quirks, otherwise the iNES header is what determines everything. Games don't actually need to be in the database to work most of the time.

**Comment by inactive123** [comment]
See my comment here - 
https://github.com/libretro/nestopia/pull/28#issuecomment-801571278

**Comment by inactive123** [comment]
So in summary - 

I still would like it to remain baked-in. However, there should be the ability to override it through sensible means by way of an external file dropped in some dir. Not sure if it is already like that. If it is, I don't really see the issue. The vast majority of users are not going to have this file to begin with so not baking it in at all is literally a net negative. This is all about user convenience and providing them with everything they need in a core to make sure as much works out of the box as possible.

**Comment by hizzlekizzle** [comment]
It'd probably be a good idea to verify whether the bake-in broke the core on 3DS and PSP, as a number of users have reported. It's possible that the reports are spurious/inaccurate, but they all popped up right after.

**Comment by troyjfarrell** [comment]
@clobber [pointed out](https://github.com/OpenEmu/Nestopia-Core/issues/6#issuecomment-807267707) that the [upstream repository](https://gitlab.com/jgemu/nestopia) [added the entry for Micro Mages](https://gitlab.com/jgemu/nestopia/-/commit/8fff696731ffc50e881924cbaebcaffd35bbb0a5) recently.

**Comment by keithbowes** [comment]
Yeah, @troyjfarrell, I assume it'll make it into Nestopia 1.52.

**Comment by RokkumanX** [comment]
For anyone wanting to have the latest Nestopia core with the closed PR @keithbowes did here it is:

[nestopia_libretro.zip](https://github.com/libretro/nestopia/files/6686655/nestopia_libretro.zip)

**Comment by Squid0000** [comment]
Ah, I feared this was the case.

From a post I made on the libretro discord:

 `Does the nestopia UE core actually utilise the NstDatabase.xml file? Games like 'Akumajou Special - Boku Dracula-kun' seem to boot just fine without it. But rom hacks don't. I have to add an entry with the new hashes to get rom hacks to boot on the nestopia win binary (v1.51.1). But no dice on the retroarch core version.`

So it's optional but doesn't do anything?  If it exists in retroarch's system folder it should override the internal database, the same way pointing to an external database behaves in the win binary.

**Comment by keithbowes** [comment]
> So it's optional but doesn't do anything? If it exists in retroarch's system folder it should override the internal database, the same way pointing to an external database behaves in the win binary.

The documentation is outdated and I've been meaning to update it but I haven't gotten around to it.  Yes, NstDatabase.xml does absolutely nothing in the Nestopia core versions 1.50 and later.  I made a Python script to allow you to change the internal database (which means that you'd have to recompile the core with the new internal database if you make any changes); that's the best I could get by twinaphex.
