### ISSUE TITLE
is there a chance to add up Mono-stereo option to alternate within RetroArch ?

### ISSUE THREAD

**Issue by nad53** [libretro/nestopia#40]
It may sound a bit picky but Nestopia standalone emulator has this little option to switch between mono and stereo, and would like to get it into RetroArch for full portability coming from the standalone.

Thanks for any reply !

**Comment by keithbowes** [comment]
Well, currently, the Nestopia core doesn't use real stereo.  It actually uses mono and sends the same audio data to both speakers.  Changing it so that the backend sends stereo data causes a crash.  However, it is very trivial to change the code so that the audio data is sent to one speaker instead of two.
