### ISSUE TITLE
[3DS] Slowdown with Mask Overscan (Horizontal) enabled

### ISSUE THREAD

**Issue by Wacko22** [libretro/nestopia#84]
Turning on Mask Overscan (Horizontal) causes a FPS drop from 60 to sub-40. This isn't an issue with Mask Overscan (Vertical). Having both options enabled at the same time gives the same sub-40 performance, the effect doesn't double/get worse.

System: New 3DS
Versions: Noticed in nestopia builds from various RetroArch releases 1.3.3 - 1.7.3.
Settings used: rgui, turned off RetroArch's own Crop Overscan function just in case (no change). Others were defaults, no rewind or anything.

The Blargg NTSC filters do a similar thing where they drop the FPS down to 30.9, but that makes more sense since they are doing more processing. Is Mask Overscan (Horizontal) also doing something especially intensive?

Combining a Blargg NTSC filter and Mask Overscan (Horizontal) only drops the FPS down to 30.9, again the effect doesn't get any worse.

**Comment by rdanbrook** [comment]
More operations are being done to make these options possible. You're on a shit CPU. Not much can be done here, sorry.

**Comment by Wacko22** [comment]
Why would there need to be more operations done on horizontal overscan vs. vertical overscan? Is it really just [this bunch of inline if statements](https://github.com/libretro/nestopia/blob/master/libretro/libretro.cpp#L878)?

**Comment by rdanbrook** [comment]
Those tests are apples to oranges, as you are working with different toolchains on different platforms, and you would need to use a profiler to get true data on what's going on. The blargg filter is going to slow things down because it is extra image processing on the CPU, unlike all of the shaders available to RetroArch. When it comes to masking the horizontal pixels, that is more intense than vertical, since you are doing multiple operations per scanline versus simply skipping entire scanlines.
