### ISSUE TITLE
Game Genie Sound Distortion stays on when using a savestate in RetroArch.

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/nestopia#87]
When using Game Genie Sound Distortion with a savestate  it will stay on even if you turn it off. try on Mage Man 2

**Comment by carmiker** [comment]
Yes, this is expected. The reason it works this way is because that option sets some register values at boot time, which affect the game for the rest of the time it runs. If you load a state where those registers were set in this way at boot, then this is going to be the result. I believe the original cause of this on real hardware was that the Game Genie sets some register values, and Mega Man, and Mega Man 2 simply don't do anything to ensure those registers are cleared, where most games either do that, or are written such that it won't really make a difference during gameplay.
