### ISSUE TITLE
Arkanoid controller support

### ISSUE THREAD

**Issue by ThatLordGuy** [libretro/nestopia#9]
Presently quicknes is the only core able to play Arkanoid as it is the only core accepting directional pad inputs in place of the bundled controller.

**Comment by JukePlz** [comment]
The standalone version of Nestopia already supports most expansion port peripherals (including arkanoid), I think it's a matter of exposing the option to enable them to the frontend's core options... but Nestopia does this through using the mouse instead of converting the d-pad inputs, so I'm not sure it wouldn't conflict somewhere with retroarch retropad implementation.

**Comment by ThatLordGuy** [comment]
I'm aware the standalone supports alternative controllers. If this git was for the standalone and not the libretro version I wouldn't have opened an issue. The quicknes solution works fine I just hate being forced to use a separate core for a single game.

**Comment by keithbowes** [comment]
I don't see why it wouldn't be possible to hook it up to the d-pad.  Surely, you'd just set the Paddle class's x member when the left and right buttons are pressed and fire when A or B is pressed.  It sounds fairly straightforward to me, but I suppose I could be underestimating the difficulty.

**Comment by keithbowes** [comment]
It seems that QuickNES can handle it through the d-pad because it doesn't support Arkanoid controllers or any other kind of peripherals.  This seems to be handled by the game itself, in case you're using standard controllers instead of an Arkanoid controller.

The same could be accomplished by setting Nestopia's Port 2 Control from Auto to Gamepad (you can create a remap file or settings override for Arkanoid to make that automatic).  Other solutions would be to get one of the free (as in beer) homebrew Breakout implementations (e.g. [Retroid](https://the-green-screen.com/292-2/#welcome) for Game Boy) or a standalone one (e.g. [LBreakout2](https://lgames.sourceforge.io/LBreakout2/)).

Nevertheless, I'll send in a PR for Arkanoid controller support.
